version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "App"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-abkhehhsi72q"
s3_prefix = "App"
region = "ap-southeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
