name: InterviewPrep

on:
  push:
    branches: [main]

jobs:
  rust-tests:
    name: Rust tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
      - name: Run Rust tests
        run: |
          cd interview_prep/algorithm/rust
          cargo test

  python-tests:
    name: Python tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Run Python tests
        run: |
          cd interview_prep/algorithm/python3
          python3 -m unittest discover -s . -p '*test.py'

  java-tests:
    name: Java tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
      - name: Build and test Java
        run: |
          cd interview_prep/algorithm/java17
          ./mvnw test