name: InterviewPrep

on:
  push:
    branches: [main]

jobs:
  rust-tests:
    name: Rust tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
      - name: Run Rust tests
        run: |
          cd interview_prep/algorithm/rust
          cargo test

  python-tests:
    name: Python tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Run Python tests
        run: |
          cd interview_prep/algorithm/python3
          python3 -m unittest discover -s . -p '*test.py'

  java-tests:
    name: Java tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'corretto'
      - name: Build and test Java
        run: |
          cd interview_prep/algorithm/java
          ./mvnw test

  typescipt-tests:
    name: Typescript tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Build and test Typescript
        run: |
          cd interview_prep/algorithm/ts
          npm i -D typescript jest ts-jest @types/jest
          npm test       